## A/B testing 

## all these measurment's is for the test 
## We discuss the behavior of two test groups in humanities and mathematics exams
## Here we have taken tests from our own mathematics lessons and in the human who is group B from different items to evaluate in different conditions

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
a = np.array([19,14,12,10,14,20,7,12,17,16,11,10]) # random array (confidence level is set) 0-20
b = np.array([18,18,17,12,14,20,11,16,15,14,17,11,20])

In [3]:
a.mean()

13.5

In [4]:
b.mean()

15.615384615384615

In [5]:
c = b.mean() - a.mean()
c

2.115384615384615

Distance and difference = 0.07692307692307665

In [6]:
np.ones(len(b)) # makes one as length of the b 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.append(np.zeros(len(a)),np.ones(len(b)))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
overall = np.array([
    np.append(np.zeros(len(a)),np.ones(len(b))),
    np.append(a,b)
])

In [9]:
overall

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [19., 14., 12., 10., 14., 20.,  7., 12., 17., 16., 11., 10., 18.,
        18., 17., 12., 14., 20., 11., 16., 15., 14., 17., 11., 20.]])

In [10]:
overall_t = overall.T # transposing (change the rows and columns of the array and sort them)

In [11]:
overall_t

array([[ 0., 19.],
       [ 0., 14.],
       [ 0., 12.],
       [ 0., 10.],
       [ 0., 14.],
       [ 0., 20.],
       [ 0.,  7.],
       [ 0., 12.],
       [ 0., 17.],
       [ 0., 16.],
       [ 0., 11.],
       [ 0., 10.],
       [ 1., 18.],
       [ 1., 18.],
       [ 1., 17.],
       [ 1., 12.],
       [ 1., 14.],
       [ 1., 20.],
       [ 1., 11.],
       [ 1., 16.],
       [ 1., 15.],
       [ 1., 14.],
       [ 1., 17.],
       [ 1., 11.],
       [ 1., 20.]])

In [12]:
np.random.shuffle(overall_t)

In [13]:
overall_t

array([[ 1., 14.],
       [ 1., 17.],
       [ 0.,  7.],
       [ 0., 12.],
       [ 0., 14.],
       [ 0., 16.],
       [ 0., 17.],
       [ 1., 17.],
       [ 1., 16.],
       [ 1., 11.],
       [ 0., 20.],
       [ 1., 15.],
       [ 1., 11.],
       [ 1., 20.],
       [ 0., 12.],
       [ 0., 14.],
       [ 1., 18.],
       [ 0., 10.],
       [ 1., 20.],
       [ 0., 19.],
       [ 1., 14.],
       [ 0., 10.],
       [ 1., 12.],
       [ 0., 11.],
       [ 1., 18.]])

In [14]:
understanding_label = np.random.randint(0,2,len(overall_t))
understanding_label

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0])

In [15]:
understanding_data = np.array([
    understanding_label,
    overall_t[:,1]
])
understanding_data

array([[ 0.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,
         1.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  0.],
       [14., 17.,  7., 12., 14., 16., 17., 17., 16., 11., 20., 15., 11.,
        20., 12., 14., 18., 10., 20., 19., 14., 10., 12., 11., 18.]])

In [16]:
understanding_data_t = understanding_data.T
understanding_data_t

array([[ 0., 14.],
       [ 1., 17.],
       [ 1.,  7.],
       [ 0., 12.],
       [ 0., 14.],
       [ 0., 16.],
       [ 1., 17.],
       [ 0., 17.],
       [ 1., 16.],
       [ 0., 11.],
       [ 1., 20.],
       [ 0., 15.],
       [ 1., 11.],
       [ 1., 20.],
       [ 1., 12.],
       [ 0., 14.],
       [ 1., 18.],
       [ 1., 10.],
       [ 0., 20.],
       [ 0., 19.],
       [ 0., 14.],
       [ 1., 10.],
       [ 1., 12.],
       [ 1., 11.],
       [ 0., 18.]])

In [17]:
understanding_data_t[understanding_data_t[:,0]==1][:,1]

array([17.,  7., 17., 16., 20., 11., 20., 12., 18., 10., 10., 12., 11.])

In [18]:
understanding_data_t[understanding_data_t[:,0]==0][:,1]

array([14., 12., 14., 16., 17., 11., 15., 14., 20., 19., 14., 18.])

In [19]:
understanding_data_t[understanding_data_t[:,0]==0][:,1].mean()

15.333333333333334

In [20]:
understanding_data_t[understanding_data_t[:,0]==1][:,1].mean()

13.923076923076923

In [21]:
np.empty([10,1])

array([[6.23042070e-307],
       [4.67296746e-307],
       [1.69121096e-306],
       [3.33772792e-307],
       [6.23047503e-307],
       [2.22526399e-307],
       [6.23053614e-307],
       [7.56592338e-307],
       [9.34588061e-307],
       [3.62651150e-317]])

In [22]:
understanding_diff_mean = np.empty([150,1])

In [23]:
for times in np.arange(150):
            understanding_label = np.random.randint(0,2,len(overall_t))
            understanding_data = np.array([
                 understanding_label,
                 overall_t[:,1]
         ]).T

In [24]:
understanding_diff_mean[times] =  understanding_data[understanding_data[:,0]==1].mean() - understanding_data[understanding_data[:,0]==0].mean()

In [25]:
e1 = understanding_diff_mean
e1

array([[6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95215176e-310],
       [6.95

In [26]:
len(e1[e1 >= c])

0